# Generated by Django 5.2.3 on 2025-06-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_instagramreel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('wedding_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(upload_to='couple_photos/covers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CouplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='couple_photos/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core_app.couple')),
            ],
        ),
    ]
