# Generated by Django 5.2.3 on 2025-06-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_couple_couplephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/uploads/random_photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Random Photo',
                'verbose_name_plural': 'Random Photos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
